/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTravauxRouteImport } from './routes/_authenticated/travaux'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedReclamationsRouteImport } from './routes/_authenticated/reclamations'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedImpayesRouteImport } from './routes/_authenticated/impayes'
import { Route as AuthenticatedEtatsDesLieuxRouteImport } from './routes/_authenticated/etats-des-lieux'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratsRouteImport } from './routes/_authenticated/contrats'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedChargesRouteImport } from './routes/_authenticated/charges'
import { Route as AuthenticatedBiensRouteImport } from './routes/_authenticated/biens'
import { Route as AuthenticatedBiensBienIdRouteImport } from './routes/_authenticated/biens.$bienId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTravauxRoute = AuthenticatedTravauxRouteImport.update({
  id: '/travaux',
  path: '/travaux',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReclamationsRoute =
  AuthenticatedReclamationsRouteImport.update({
    id: '/reclamations',
    path: '/reclamations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpayesRoute = AuthenticatedImpayesRouteImport.update({
  id: '/impayes',
  path: '/impayes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtatsDesLieuxRoute =
  AuthenticatedEtatsDesLieuxRouteImport.update({
    id: '/etats-des-lieux',
    path: '/etats-des-lieux',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratsRoute = AuthenticatedContratsRouteImport.update({
  id: '/contrats',
  path: '/contrats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChargesRoute = AuthenticatedChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiensRoute = AuthenticatedBiensRouteImport.update({
  id: '/biens',
  path: '/biens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiensBienIdRoute =
  AuthenticatedBiensBienIdRouteImport.update({
    id: '/$bienId',
    path: '/$bienId',
    getParentRoute: () => AuthenticatedBiensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biens': typeof AuthenticatedBiensRouteWithChildren
  '/charges': typeof AuthenticatedChargesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contrats': typeof AuthenticatedContratsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etats-des-lieux': typeof AuthenticatedEtatsDesLieuxRoute
  '/impayes': typeof AuthenticatedImpayesRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/reclamations': typeof AuthenticatedReclamationsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/travaux': typeof AuthenticatedTravauxRoute
  '/users': typeof AuthenticatedUsersRoute
  '/biens/$bienId': typeof AuthenticatedBiensBienIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biens': typeof AuthenticatedBiensRouteWithChildren
  '/charges': typeof AuthenticatedChargesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/contrats': typeof AuthenticatedContratsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etats-des-lieux': typeof AuthenticatedEtatsDesLieuxRoute
  '/impayes': typeof AuthenticatedImpayesRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/reclamations': typeof AuthenticatedReclamationsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/travaux': typeof AuthenticatedTravauxRoute
  '/users': typeof AuthenticatedUsersRoute
  '/biens/$bienId': typeof AuthenticatedBiensBienIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/biens': typeof AuthenticatedBiensRouteWithChildren
  '/_authenticated/charges': typeof AuthenticatedChargesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/contrats': typeof AuthenticatedContratsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/etats-des-lieux': typeof AuthenticatedEtatsDesLieuxRoute
  '/_authenticated/impayes': typeof AuthenticatedImpayesRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/reclamations': typeof AuthenticatedReclamationsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/travaux': typeof AuthenticatedTravauxRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/biens/$bienId': typeof AuthenticatedBiensBienIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biens'
    | '/charges'
    | '/contacts'
    | '/contrats'
    | '/dashboard'
    | '/etats-des-lieux'
    | '/impayes'
    | '/imports'
    | '/reclamations'
    | '/transactions'
    | '/travaux'
    | '/users'
    | '/biens/$bienId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biens'
    | '/charges'
    | '/contacts'
    | '/contrats'
    | '/dashboard'
    | '/etats-des-lieux'
    | '/impayes'
    | '/imports'
    | '/reclamations'
    | '/transactions'
    | '/travaux'
    | '/users'
    | '/biens/$bienId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/biens'
    | '/_authenticated/charges'
    | '/_authenticated/contacts'
    | '/_authenticated/contrats'
    | '/_authenticated/dashboard'
    | '/_authenticated/etats-des-lieux'
    | '/_authenticated/impayes'
    | '/_authenticated/imports'
    | '/_authenticated/reclamations'
    | '/_authenticated/transactions'
    | '/_authenticated/travaux'
    | '/_authenticated/users'
    | '/_authenticated/biens/$bienId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travaux': {
      id: '/_authenticated/travaux'
      path: '/travaux'
      fullPath: '/travaux'
      preLoaderRoute: typeof AuthenticatedTravauxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reclamations': {
      id: '/_authenticated/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof AuthenticatedReclamationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impayes': {
      id: '/_authenticated/impayes'
      path: '/impayes'
      fullPath: '/impayes'
      preLoaderRoute: typeof AuthenticatedImpayesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etats-des-lieux': {
      id: '/_authenticated/etats-des-lieux'
      path: '/etats-des-lieux'
      fullPath: '/etats-des-lieux'
      preLoaderRoute: typeof AuthenticatedEtatsDesLieuxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contrats': {
      id: '/_authenticated/contrats'
      path: '/contrats'
      fullPath: '/contrats'
      preLoaderRoute: typeof AuthenticatedContratsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charges': {
      id: '/_authenticated/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof AuthenticatedChargesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biens': {
      id: '/_authenticated/biens'
      path: '/biens'
      fullPath: '/biens'
      preLoaderRoute: typeof AuthenticatedBiensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biens/$bienId': {
      id: '/_authenticated/biens/$bienId'
      path: '/$bienId'
      fullPath: '/biens/$bienId'
      preLoaderRoute: typeof AuthenticatedBiensBienIdRouteImport
      parentRoute: typeof AuthenticatedBiensRoute
    }
  }
}

interface AuthenticatedBiensRouteChildren {
  AuthenticatedBiensBienIdRoute: typeof AuthenticatedBiensBienIdRoute
}

const AuthenticatedBiensRouteChildren: AuthenticatedBiensRouteChildren = {
  AuthenticatedBiensBienIdRoute: AuthenticatedBiensBienIdRoute,
}

const AuthenticatedBiensRouteWithChildren =
  AuthenticatedBiensRoute._addFileChildren(AuthenticatedBiensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBiensRoute: typeof AuthenticatedBiensRouteWithChildren
  AuthenticatedChargesRoute: typeof AuthenticatedChargesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedContratsRoute: typeof AuthenticatedContratsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEtatsDesLieuxRoute: typeof AuthenticatedEtatsDesLieuxRoute
  AuthenticatedImpayesRoute: typeof AuthenticatedImpayesRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedReclamationsRoute: typeof AuthenticatedReclamationsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedTravauxRoute: typeof AuthenticatedTravauxRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBiensRoute: AuthenticatedBiensRouteWithChildren,
  AuthenticatedChargesRoute: AuthenticatedChargesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedContratsRoute: AuthenticatedContratsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEtatsDesLieuxRoute: AuthenticatedEtatsDesLieuxRoute,
  AuthenticatedImpayesRoute: AuthenticatedImpayesRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedReclamationsRoute: AuthenticatedReclamationsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedTravauxRoute: AuthenticatedTravauxRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
